---
title: "John Yeiser's Research"
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Wildife in Working Lands

Lands used to produce food and goods are home a substantial portion of the world's biodiversity. To keep up with the growing needs of human populations, working lands are expanding and intensifying, often simultaneously. It is important that we understand how these processes moderate ecosystem services, biodiversity, and outdoor recreation opportunities. 

We have a good idea of how conservation on working lands influences wildlife at local scales. Typically, conservation measures improve habitat quality for target species at the parcel scale and may result in greater local abundances. We know less about the degree to which these effects permeate into the landscape via population-level processes (e.g., dispersal). My focus has been on estimating the landscape-scale effects of conservation on bird populations in agricultural ecosystems. 

Major themes: broad-scale study design; landscape ecology; advanced distance sampling models; machine learning; habitat management; spatially explicit decision support tools; fostering partnerships

#### Projects

#### 1. Prioritizing grassland conservation for birds in agricultural landscapes



### Applied Landscape Ecology

Resource management agencies are tasked with stewarding fish and wildlife populations to meet the demands of stakeholders (e.g., the public). This requires agencies to understand how the number and condition of individuals in populations vary over space and time. Understanding how populations change in response to conservation actions is particularly informative to the decision-making process that managers undertake. I work with agency partners to design research studies that will directly inform management or conservation decisions. Since these decisions impact resources across large areas for a long period of time, I use spatial and landscape ecology theory to inform these research projects.

Wildlife often occur in fragmented systems with variable surroundings, so there is rarely a one-size-fits-all management recommendation from our research. My colleagues and I apply our research to on-the-ground conservation by building decision support tools that can optimize conservation efforts in differing landscape contexts.

### Adaptive Management

Many resource managers have mental models about the system in which they work. For example, a manager may think that chick survival is what bobwhite quail are missing on their management area. After they implement a management action to remedy the situation (e.g., improve brood-rearing cover), they assess the population and update their hypothesis. If the population goes up, they may conclude that chick survival was indeed limiting populations. If the population goes down or stays static, then they may conclude that some other factor is limiting population growth. 

Adaptive management is a great way to transfer mental models into a structured decision framework. My colleagues and I work directly with resource management agencies to identify problems and objectives, state and implement alternative management actions, and monitor and analyze the response of wildlife populations to those actions. At the end of this cycle, we can update our beliefs about which management alternative best meets their objectives. In theory, this process is repeated until the uncertainty around how the system works is very low.

### Applied Simulation Modeling

Manipulative studies on wildlife populations are difficult because of the sample size requirements of common statistical analyses and the geographic and temporal scale at which populations operate. Simulation models are powerful tools that allow us to combine the results of small scale studies (e.g., vital rates estimated at different wildlife management areas) into comprehensive population simulation models. My colleagues and I use simulation models to hypothesize about the consequences of management actions on wildlife populations at large scales. We also use simulation modeling to inform our research study designs.
